// State-specific NDA provisions and enforceability rules

export interface StateNDAProvisions {
  code: string;
  name: string;
  governingLawLanguage: string;
  venueLanguage: string;
  enforceabilityNotes: string;
  nonCompeteStatus: 'enforceable' | 'limited' | 'unenforceable';
  nonCompeteRestrictions: string;
  tradeSecretStatute: string;
  tradeSecretStatuteName: string;
  remedies: {
    injunctiveRelief: string;
    damages: string;
    attorneysFees: string;
  };
}

export const NDA_STATE_PROVISIONS: Record<string, StateNDAProvisions> = {
  AL: {
    code: 'AL',
    name: 'Alabama',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Alabama, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Alabama.',
    enforceabilityNotes: 'Alabama courts generally enforce reasonable NDAs.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in time, geography, and scope.',
    tradeSecretStatute: 'Ala. Code § 8-27-1 et seq.',
    tradeSecretStatuteName: 'Alabama Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages or unjust enrichment.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  AK: {
    code: 'AK',
    name: 'Alaska',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Alaska, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Alaska.',
    enforceabilityNotes: 'Alaska courts enforce NDAs that protect legitimate business interests.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must protect legitimate business interests and be reasonable.',
    tradeSecretStatute: 'AS § 45.50.910 et seq.',
    tradeSecretStatuteName: 'Alaska Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available to prevent actual or threatened misappropriation.',
      damages: 'Actual loss and unjust enrichment.',
      attorneysFees: 'Available for bad faith claims or willful misappropriation.',
    },
  },
  AZ: {
    code: 'AZ',
    name: 'Arizona',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Arizona, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Maricopa County, Arizona.',
    enforceabilityNotes: 'Arizona has adopted the UTSA and enforces NDAs protecting trade secrets.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be ancillary to employment and reasonable in scope.',
    tradeSecretStatute: 'A.R.S. § 44-401 et seq.',
    tradeSecretStatuteName: 'Arizona Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for actual or threatened misappropriation.',
      damages: 'Compensatory damages including lost profits.',
      attorneysFees: 'May be awarded in cases of willful misappropriation.',
    },
  },
  AR: {
    code: 'AR',
    name: 'Arkansas',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Arkansas, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Arkansas.',
    enforceabilityNotes: 'Arkansas enforces NDAs as part of its trade secret protection framework.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Reasonable restrictions enforceable; courts may blue-pencil.',
    tradeSecretStatute: 'Ark. Code Ann. § 4-75-601 et seq.',
    tradeSecretStatuteName: 'Arkansas Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'Available for willful and malicious misappropriation.',
    },
  },
  CA: {
    code: 'CA',
    name: 'California',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in California.',
    enforceabilityNotes: 'California strongly enforces NDAs but prohibits most non-compete agreements under Business & Professions Code § 16600.',
    nonCompeteStatus: 'unenforceable',
    nonCompeteRestrictions: 'Non-compete clauses are generally void and unenforceable under B&P Code § 16600. Limited exceptions for sale of business.',
    tradeSecretStatute: 'Cal. Civ. Code § 3426 et seq.',
    tradeSecretStatuteName: 'California Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available; court may condition on posting bond.',
      damages: 'Actual loss, unjust enrichment, and exemplary damages up to 2x for willful misappropriation.',
      attorneysFees: 'Available for bad faith claims or willful and malicious misappropriation.',
    },
  },
  CO: {
    code: 'CO',
    name: 'Colorado',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Colorado, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Denver, Colorado.',
    enforceabilityNotes: 'Colorado enforces NDAs and has specific restrictions on non-competes.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes void except for executive/management personnel, sale of business, or protection of trade secrets (C.R.S. § 8-2-113).',
    tradeSecretStatute: 'C.R.S. § 7-74-101 et seq.',
    tradeSecretStatuteName: 'Colorado Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  CT: {
    code: 'CT',
    name: 'Connecticut',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Connecticut, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Connecticut.',
    enforceabilityNotes: 'Connecticut courts enforce reasonable NDAs protecting legitimate business interests.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in time, geographic scope, and protect legitimate business interests.',
    tradeSecretStatute: 'Conn. Gen. Stat. § 35-50 et seq.',
    tradeSecretStatuteName: 'Connecticut Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual loss and unjust enrichment.',
      attorneysFees: 'Available if misappropriation is willful and malicious.',
    },
  },
  DE: {
    code: 'DE',
    name: 'Delaware',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the Court of Chancery of the State of Delaware, or if such court lacks jurisdiction, the state or federal courts located in Delaware.',
    enforceabilityNotes: 'Delaware is business-friendly with strong NDA enforcement. The Court of Chancery provides expedited injunctive relief.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Reasonableness test applies; Delaware courts generally enforce reasonable restrictions.',
    tradeSecretStatute: '6 Del. C. § 2001 et seq.',
    tradeSecretStatuteName: 'Delaware Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Chancery Court provides expedited injunctive relief.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  FL: {
    code: 'FL',
    name: 'Florida',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Florida, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Florida.',
    enforceabilityNotes: 'Florida has a strong trade secrets act and enforces NDAs. Non-competes are enforceable under Fla. Stat. § 542.335.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be in writing, signed, reasonably necessary to protect legitimate business interests, and reasonable in time/area/scope.',
    tradeSecretStatute: 'Fla. Stat. § 688.001 et seq.',
    tradeSecretStatuteName: 'Florida Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment; exemplary damages up to 2x for willful misappropriation.',
      attorneysFees: 'May be awarded under Fla. Stat. § 688.005.',
    },
  },
  GA: {
    code: 'GA',
    name: 'Georgia',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Georgia, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Georgia.',
    enforceabilityNotes: 'Georgia enforces NDAs and restrictive covenants under the Georgia Restrictive Covenants Act.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Georgia Restrictive Covenants Act (O.C.G.A. § 13-8-50 et seq.) allows reasonable restrictions.',
    tradeSecretStatute: 'O.C.G.A. § 10-1-760 et seq.',
    tradeSecretStatuteName: 'Georgia Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for threatened or actual misappropriation.',
      damages: 'Actual damages, unjust enrichment, and punitive damages for willful misappropriation.',
      attorneysFees: 'May be awarded in cases of bad faith or willful misconduct.',
    },
  },
  HI: {
    code: 'HI',
    name: 'Hawaii',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Hawaii, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Honolulu, Hawaii.',
    enforceabilityNotes: 'Hawaii enforces NDAs and has adopted the UTSA.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes in technology sector prohibited (HRS § 480-4). Other industries may enforce reasonable restrictions.',
    tradeSecretStatute: 'HRS § 482B-1 et seq.',
    tradeSecretStatuteName: 'Hawaii Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  ID: {
    code: 'ID',
    name: 'Idaho',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Idaho, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Idaho.',
    enforceabilityNotes: 'Idaho courts enforce reasonable NDAs and restrictive covenants.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable and supported by consideration.',
    tradeSecretStatute: 'Idaho Code § 48-801 et seq.',
    tradeSecretStatuteName: 'Idaho Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  IL: {
    code: 'IL',
    name: 'Illinois',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Illinois, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Cook County, Illinois.',
    enforceabilityNotes: 'Illinois enforces NDAs and has specific requirements for non-competes under the Illinois Freedom to Work Act.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Illinois Freedom to Work Act restricts non-competes for employees earning less than $75,000 (threshold increases annually).',
    tradeSecretStatute: '765 ILCS 1065/1 et seq.',
    tradeSecretStatuteName: 'Illinois Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available under the Act.',
      damages: 'Actual damages and unjust enrichment; exemplary damages up to 2x.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  IN: {
    code: 'IN',
    name: 'Indiana',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Indiana, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Indiana.',
    enforceabilityNotes: 'Indiana enforces reasonable NDAs and non-compete agreements.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in scope, time, and geography.',
    tradeSecretStatute: 'Ind. Code § 24-2-3-1 et seq.',
    tradeSecretStatuteName: 'Indiana Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  IA: {
    code: 'IA',
    name: 'Iowa',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Iowa, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Iowa.',
    enforceabilityNotes: 'Iowa courts enforce reasonable NDAs and restrictive covenants.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable and supported by valid consideration.',
    tradeSecretStatute: 'Iowa Code § 550.1 et seq.',
    tradeSecretStatuteName: 'Iowa Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  KS: {
    code: 'KS',
    name: 'Kansas',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Kansas, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Kansas.',
    enforceabilityNotes: 'Kansas enforces NDAs and reasonable restrictive covenants.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in duration, geographic scope, and activity restricted.',
    tradeSecretStatute: 'K.S.A. § 60-3320 et seq.',
    tradeSecretStatuteName: 'Kansas Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  KY: {
    code: 'KY',
    name: 'Kentucky',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the Commonwealth of Kentucky, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Kentucky.',
    enforceabilityNotes: 'Kentucky courts enforce reasonable NDAs and restrictive covenants.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in scope and protect legitimate business interests.',
    tradeSecretStatute: 'KRS § 365.880 et seq.',
    tradeSecretStatuteName: 'Kentucky Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  LA: {
    code: 'LA',
    name: 'Louisiana',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Louisiana, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Louisiana.',
    enforceabilityNotes: 'Louisiana has specific statutory requirements for non-competes but enforces NDAs.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes must specify parishes or municipalities and cannot exceed 2 years (La. R.S. 23:921).',
    tradeSecretStatute: 'La. R.S. 51:1431 et seq.',
    tradeSecretStatuteName: 'Louisiana Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  ME: {
    code: 'ME',
    name: 'Maine',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Maine, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Maine.',
    enforceabilityNotes: 'Maine enforces NDAs and has recent restrictions on non-competes.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Cannot be enforced against employees earning less than 400% of federal poverty level; requires 3 days notice before signing.',
    tradeSecretStatute: '10 M.R.S. § 1541 et seq.',
    tradeSecretStatuteName: 'Maine Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  MD: {
    code: 'MD',
    name: 'Maryland',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Maryland, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Maryland.',
    enforceabilityNotes: 'Maryland enforces NDAs and has restrictions on non-competes for low-wage workers.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes unenforceable for employees earning equal to or less than $15/hour or $31,200/year.',
    tradeSecretStatute: 'Md. Code, Com. Law § 11-1201 et seq.',
    tradeSecretStatuteName: 'Maryland Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages, unjust enrichment, and exemplary damages up to 2x.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  MA: {
    code: 'MA',
    name: 'Massachusetts',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the Commonwealth of Massachusetts, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Massachusetts.',
    enforceabilityNotes: 'Massachusetts has the Massachusetts Noncompetition Agreement Act with specific requirements.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes limited to 12 months, require garden leave or consideration, and cannot apply to non-exempt employees.',
    tradeSecretStatute: 'M.G.L. c. 93 § 42 et seq.',
    tradeSecretStatuteName: 'Massachusetts Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages, unjust enrichment, and exemplary damages up to 2x.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  MI: {
    code: 'MI',
    name: 'Michigan',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Michigan, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Michigan.',
    enforceabilityNotes: 'Michigan enforces reasonable NDAs under the Michigan Antitrust Reform Act.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Enforceable if reasonable in duration, geographic scope, and type of employment (MCL 445.774a).',
    tradeSecretStatute: 'MCL § 445.1901 et seq.',
    tradeSecretStatuteName: 'Michigan Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  MN: {
    code: 'MN',
    name: 'Minnesota',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Minnesota, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Hennepin County, Minnesota.',
    enforceabilityNotes: 'Minnesota recently banned most non-compete agreements but enforces NDAs.',
    nonCompeteStatus: 'unenforceable',
    nonCompeteRestrictions: 'As of July 1, 2023, non-competes are largely unenforceable. Non-solicitation and NDAs remain enforceable.',
    tradeSecretStatute: 'Minn. Stat. § 325C.01 et seq.',
    tradeSecretStatuteName: 'Minnesota Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  MS: {
    code: 'MS',
    name: 'Mississippi',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Mississippi, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Mississippi.',
    enforceabilityNotes: 'Mississippi courts enforce reasonable NDAs and restrictive covenants.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in time and scope; courts may blue-pencil unreasonable provisions.',
    tradeSecretStatute: 'Miss. Code Ann. § 75-26-1 et seq.',
    tradeSecretStatuteName: 'Mississippi Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  MO: {
    code: 'MO',
    name: 'Missouri',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Missouri, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Missouri.',
    enforceabilityNotes: 'Missouri enforces NDAs and reasonable restrictive covenants.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable and necessary to protect legitimate business interests.',
    tradeSecretStatute: 'Mo. Rev. Stat. § 417.450 et seq.',
    tradeSecretStatuteName: 'Missouri Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  MT: {
    code: 'MT',
    name: 'Montana',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Montana, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Montana.',
    enforceabilityNotes: 'Montana generally disfavors non-competes but enforces NDAs protecting trade secrets.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes are disfavored; limited exceptions exist under Mont. Code Ann. § 28-2-703.',
    tradeSecretStatute: 'Mont. Code Ann. § 30-14-401 et seq.',
    tradeSecretStatuteName: 'Montana Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  NE: {
    code: 'NE',
    name: 'Nebraska',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Nebraska, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Nebraska.',
    enforceabilityNotes: 'Nebraska courts enforce NDAs and reasonable restrictive covenants.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in scope and duration.',
    tradeSecretStatute: 'Neb. Rev. Stat. § 87-501 et seq.',
    tradeSecretStatuteName: 'Nebraska Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  NV: {
    code: 'NV',
    name: 'Nevada',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Nevada, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Clark County, Nevada.',
    enforceabilityNotes: 'Nevada enforces NDAs and non-compete agreements under NRS 613.195.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Governed by NRS 613.195; must be reasonable and supported by valuable consideration.',
    tradeSecretStatute: 'NRS § 600A.010 et seq.',
    tradeSecretStatuteName: 'Nevada Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Actual damages, unjust enrichment, and exemplary damages up to 2x.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  NH: {
    code: 'NH',
    name: 'New Hampshire',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of New Hampshire, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in New Hampshire.',
    enforceabilityNotes: 'New Hampshire enforces NDAs and has restrictions on non-competes for low-wage workers.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Cannot require non-competes for low-wage workers earning less than 200% minimum wage.',
    tradeSecretStatute: 'RSA § 350-B:1 et seq.',
    tradeSecretStatuteName: 'New Hampshire Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  NJ: {
    code: 'NJ',
    name: 'New Jersey',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of New Jersey, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in New Jersey.',
    enforceabilityNotes: 'New Jersey courts apply a reasonableness test to restrictive covenants and enforce NDAs.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must protect legitimate business interests and be reasonable in time, scope, and geography.',
    tradeSecretStatute: 'N.J.S.A. § 56:15-1 et seq.',
    tradeSecretStatuteName: 'New Jersey Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  NM: {
    code: 'NM',
    name: 'New Mexico',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of New Mexico, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in New Mexico.',
    enforceabilityNotes: 'New Mexico courts enforce reasonable NDAs and non-compete agreements.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable and ancillary to a valid employment relationship.',
    tradeSecretStatute: 'NMSA § 57-3A-1 et seq.',
    tradeSecretStatuteName: 'New Mexico Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  NY: {
    code: 'NY',
    name: 'New York',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in New York County, New York.',
    enforceabilityNotes: 'New York courts enforce NDAs and apply a reasonableness test to non-competes.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be no greater than necessary to protect legitimate interests, not harmful to employee or public, and reasonable in time and scope.',
    tradeSecretStatute: 'Common law (no UTSA adopted)',
    tradeSecretStatuteName: 'New York Common Law Trade Secrets',
    remedies: {
      injunctiveRelief: 'Injunctive relief available under common law.',
      damages: 'Compensatory damages and unjust enrichment.',
      attorneysFees: 'Generally not available unless contractually provided.',
    },
  },
  NC: {
    code: 'NC',
    name: 'North Carolina',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of North Carolina, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in North Carolina.',
    enforceabilityNotes: 'North Carolina enforces NDAs and reasonable non-compete agreements.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must protect legitimate business interests and be reasonable in time (generally 2-5 years max) and geography.',
    tradeSecretStatute: 'N.C. Gen. Stat. § 66-152 et seq.',
    tradeSecretStatuteName: 'North Carolina Trade Secrets Protection Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  ND: {
    code: 'ND',
    name: 'North Dakota',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of North Dakota, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in North Dakota.',
    enforceabilityNotes: 'North Dakota generally voids non-compete agreements but enforces NDAs protecting trade secrets.',
    nonCompeteStatus: 'unenforceable',
    nonCompeteRestrictions: 'Non-competes generally void under N.D. Cent. Code § 9-08-06. Limited exceptions for sale of business.',
    tradeSecretStatute: 'N.D. Cent. Code § 47-25.1-01 et seq.',
    tradeSecretStatuteName: 'North Dakota Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  OH: {
    code: 'OH',
    name: 'Ohio',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Ohio, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Ohio.',
    enforceabilityNotes: 'Ohio courts enforce reasonable NDAs and non-compete agreements.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in geographic and temporal scope; courts may blue-pencil.',
    tradeSecretStatute: 'Ohio Rev. Code § 1333.61 et seq.',
    tradeSecretStatuteName: 'Ohio Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  OK: {
    code: 'OK',
    name: 'Oklahoma',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Oklahoma, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Oklahoma.',
    enforceabilityNotes: 'Oklahoma generally voids non-competes but enforces NDAs and non-solicitation agreements.',
    nonCompeteStatus: 'unenforceable',
    nonCompeteRestrictions: 'Non-competes generally void under 15 O.S. § 219A. Non-solicitation of established customers may be enforceable.',
    tradeSecretStatute: '78 O.S. § 85 et seq.',
    tradeSecretStatuteName: 'Oklahoma Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  OR: {
    code: 'OR',
    name: 'Oregon',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Oregon, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Oregon.',
    enforceabilityNotes: 'Oregon has specific statutory requirements for non-compete agreements.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes limited to 18 months, require 2 weeks advance notice, and employee must earn above median income (ORS 653.295).',
    tradeSecretStatute: 'ORS § 646.461 et seq.',
    tradeSecretStatuteName: 'Oregon Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  PA: {
    code: 'PA',
    name: 'Pennsylvania',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the Commonwealth of Pennsylvania, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Pennsylvania.',
    enforceabilityNotes: 'Pennsylvania courts enforce reasonable NDAs and non-compete agreements.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be ancillary to employment, supported by consideration, and reasonable in scope.',
    tradeSecretStatute: '12 Pa.C.S. § 5301 et seq.',
    tradeSecretStatuteName: 'Pennsylvania Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  RI: {
    code: 'RI',
    name: 'Rhode Island',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Rhode Island, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Rhode Island.',
    enforceabilityNotes: 'Rhode Island enforces NDAs and has restrictions on non-competes for certain workers.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes unenforceable for low-wage workers, students, minors, and certain other categories (R.I. Gen. Laws § 28-59-3).',
    tradeSecretStatute: 'R.I. Gen. Laws § 6-41-1 et seq.',
    tradeSecretStatuteName: 'Rhode Island Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  SC: {
    code: 'SC',
    name: 'South Carolina',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of South Carolina, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in South Carolina.',
    enforceabilityNotes: 'South Carolina courts enforce reasonable NDAs and non-compete agreements.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be necessary for employer protection, reasonable in time and territory, and not unduly harsh.',
    tradeSecretStatute: 'S.C. Code Ann. § 39-8-10 et seq.',
    tradeSecretStatuteName: 'South Carolina Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  SD: {
    code: 'SD',
    name: 'South Dakota',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of South Dakota, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in South Dakota.',
    enforceabilityNotes: 'South Dakota generally disfavors non-competes but enforces NDAs.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Agreements not to compete are void unless specific exceptions apply (SDCL 53-9-8 through 53-9-11).',
    tradeSecretStatute: 'SDCL § 37-29-1 et seq.',
    tradeSecretStatuteName: 'South Dakota Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  TN: {
    code: 'TN',
    name: 'Tennessee',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Tennessee, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Tennessee.',
    enforceabilityNotes: 'Tennessee courts enforce reasonable NDAs and non-compete agreements.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in time, geography, and scope; courts may modify unreasonable provisions.',
    tradeSecretStatute: 'Tenn. Code Ann. § 47-25-1701 et seq.',
    tradeSecretStatuteName: 'Tennessee Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages, unjust enrichment, and exemplary damages up to 2x.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  TX: {
    code: 'TX',
    name: 'Texas',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Texas, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Texas.',
    enforceabilityNotes: 'Texas enforces non-competes that are ancillary to an otherwise enforceable agreement and reasonable.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be ancillary to an otherwise enforceable agreement (Tex. Bus. & Com. Code § 15.50). Courts may reform unreasonable provisions.',
    tradeSecretStatute: 'Tex. Civ. Prac. & Rem. Code § 134A.001 et seq.',
    tradeSecretStatuteName: 'Texas Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment; exemplary damages up to 2x for willful misappropriation.',
      attorneysFees: 'May be awarded under the Act.',
    },
  },
  UT: {
    code: 'UT',
    name: 'Utah',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Utah, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Utah.',
    enforceabilityNotes: 'Utah has specific statutory requirements limiting non-compete duration.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Post-employment non-competes limited to 1 year (Utah Code § 34-51-201). Exceptions for sale of business.',
    tradeSecretStatute: 'Utah Code § 13-24-1 et seq.',
    tradeSecretStatuteName: 'Utah Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  VT: {
    code: 'VT',
    name: 'Vermont',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Vermont, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Vermont.',
    enforceabilityNotes: 'Vermont courts enforce reasonable NDAs and restrictive covenants.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable and protect legitimate business interests.',
    tradeSecretStatute: '9 V.S.A. § 4601 et seq.',
    tradeSecretStatuteName: 'Vermont Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  VA: {
    code: 'VA',
    name: 'Virginia',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the Commonwealth of Virginia, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Virginia.',
    enforceabilityNotes: 'Virginia has specific restrictions on non-competes for low-wage workers.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes unenforceable for low-wage employees earning less than median Virginia household income (Va. Code § 40.1-28.7:8).',
    tradeSecretStatute: 'Va. Code § 59.1-336 et seq.',
    tradeSecretStatuteName: 'Virginia Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  WA: {
    code: 'WA',
    name: 'Washington',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Washington, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in King County, Washington.',
    enforceabilityNotes: 'Washington has significant restrictions on non-compete agreements.',
    nonCompeteStatus: 'limited',
    nonCompeteRestrictions: 'Non-competes limited to employees earning over $116,593.18 (adjusted annually) and independent contractors earning over $291,483. Maximum 18 months (RCW 49.62).',
    tradeSecretStatute: 'RCW § 19.108.010 et seq.',
    tradeSecretStatuteName: 'Washington Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages, unjust enrichment, and exemplary damages up to 2x.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
  WV: {
    code: 'WV',
    name: 'West Virginia',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of West Virginia, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in West Virginia.',
    enforceabilityNotes: 'West Virginia courts enforce reasonable NDAs and non-compete agreements.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in scope, time, and territory.',
    tradeSecretStatute: 'W. Va. Code § 47-22-1 et seq.',
    tradeSecretStatuteName: 'West Virginia Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for threatened or actual misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  WI: {
    code: 'WI',
    name: 'Wisconsin',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Wisconsin, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Wisconsin.',
    enforceabilityNotes: 'Wisconsin enforces reasonable restrictive covenants under Wis. Stat. § 103.465.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be necessary to protect employer, provide reasonable time and territory limits, and be reasonable to the employee (Wis. Stat. § 103.465).',
    tradeSecretStatute: 'Wis. Stat. § 134.90',
    tradeSecretStatuteName: 'Wisconsin Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Injunctive relief available for misappropriation.',
      damages: 'Compensatory damages and unjust enrichment.',
      attorneysFees: 'May be awarded in appropriate cases.',
    },
  },
  WY: {
    code: 'WY',
    name: 'Wyoming',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the State of Wyoming, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the state or federal courts located in Wyoming.',
    enforceabilityNotes: 'Wyoming courts enforce reasonable NDAs and non-compete agreements.',
    nonCompeteStatus: 'enforceable',
    nonCompeteRestrictions: 'Must be reasonable in scope and duration.',
    tradeSecretStatute: 'Wyo. Stat. § 40-24-101 et seq.',
    tradeSecretStatuteName: 'Wyoming Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful misappropriation.',
    },
  },
  DC: {
    code: 'DC',
    name: 'District of Columbia',
    governingLawLanguage: 'This Agreement shall be governed by and construed in accordance with the laws of the District of Columbia, without regard to its conflict of laws principles.',
    venueLanguage: 'Any dispute arising under this Agreement shall be resolved in the Superior Court of the District of Columbia or the United States District Court for the District of Columbia.',
    enforceabilityNotes: 'D.C. has largely banned non-compete agreements for most employees.',
    nonCompeteStatus: 'unenforceable',
    nonCompeteRestrictions: 'Non-competes banned for most employees under the Ban on Non-Compete Agreements Amendment Act. Limited exceptions for medical specialists and highly compensated employees.',
    tradeSecretStatute: 'D.C. Code § 36-401 et seq.',
    tradeSecretStatuteName: 'District of Columbia Uniform Trade Secrets Act',
    remedies: {
      injunctiveRelief: 'Available for actual or threatened misappropriation.',
      damages: 'Actual damages and unjust enrichment.',
      attorneysFees: 'May be awarded for willful and malicious misappropriation.',
    },
  },
};

// Helper function to get state provisions
export function getNDAStateProvisions(stateCode: string): StateNDAProvisions | undefined {
  return NDA_STATE_PROVISIONS[stateCode];
}

// NDA term length options
export const NDA_TERM_LENGTHS = [
  { value: '1', label: '1 Year', description: 'Short-term protection' },
  { value: '2', label: '2 Years', description: 'Standard protection period' },
  { value: '3', label: '3 Years', description: 'Extended protection' },
  { value: '5', label: '5 Years', description: 'Long-term protection' },
  { value: 'perpetual', label: 'Perpetual', description: 'Protection continues indefinitely' },
];

// Dispute resolution options
export const NDA_DISPUTE_RESOLUTION = [
  { value: 'litigation', label: 'Litigation', description: 'Disputes resolved in court' },
  { value: 'arbitration', label: 'Binding Arbitration', description: 'Private, binding dispute resolution' },
  { value: 'mediation', label: 'Mediation First', description: 'Attempt mediation before litigation' },
];

// NDA language style options
export const NDA_LANGUAGE_STYLES = [
  { value: 'standard', label: 'Standard', description: 'Professional business language' },
  { value: 'simplified', label: 'Simplified', description: 'Plain English, easier to understand' },
  { value: 'tightened', label: 'Tightened', description: 'More restrictive, stronger protections' },
];

// Get non-compete status badge info
export function getNonCompeteStatusInfo(status: StateNDAProvisions['nonCompeteStatus']): { 
  label: string; 
  color: string;
  description: string;
} {
  switch (status) {
    case 'enforceable':
      return { 
        label: 'Enforceable', 
        color: 'bg-green-500/10 text-green-600 dark:text-green-400',
        description: 'Non-compete clauses are generally enforceable if reasonable'
      };
    case 'limited':
      return { 
        label: 'Limited', 
        color: 'bg-amber-500/10 text-amber-600 dark:text-amber-400',
        description: 'Non-compete clauses have significant restrictions'
      };
    case 'unenforceable':
      return { 
        label: 'Unenforceable', 
        color: 'bg-red-500/10 text-red-600 dark:text-red-400',
        description: 'Non-compete clauses are generally not enforceable'
      };
  }
}
