/**
 * PRINT-ACCURATE PAGINATION STYLES
 * 
 * ══════════════════════════════════════════════════════════════════════════════
 * SINGLE SOURCE OF TRUTH for page dimensions and ALL letter styling.
 * ══════════════════════════════════════════════════════════════════════════════
 * 
 * These constants and styles are used by:
 * - PaginatedDocumentViewer (preview)
 * - PDF export (html2pdf.js)
 * - DOCX export
 * - Print
 * 
 * NON-NEGOTIABLE RULES:
 * 1. Preview and export MUST use identical dimensions
 * 2. All letter styling comes from getUnifiedLetterStyles() ONLY
 * 3. LETTER_FONT_STACK is the canonical font definition
 * 4. If preview ≠ export, it is a DEFECT
 */

// ============================================================================
// CANONICAL FONT DEFINITION
// ============================================================================

/**
 * The ONLY font stack for letter documents.
 * Used by preview, PDF export, DOCX export, and print.
 */
export const LETTER_FONT_STACK = "Arial, Calibri, 'Helvetica Neue', sans-serif";

// ============================================================================
// PAGE DIMENSION SPECIFICATIONS (96 DPI)
// ============================================================================

export type PageSize = 'letter' | 'a4';

export interface PageSpec {
  name: string;
  width: string;
  height: string;
  widthPx: number;
  heightPx: number;
  margins: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
  usableWidthPx: number;
  usableHeightPx: number;
}

/**
 * Exact page specifications at 96 DPI
 * These values are used for both preview rendering and PDF export
 */
export const PAGE_SPECS: Record<PageSize, PageSpec> = {
  letter: {
    name: 'US Letter',
    width: '8.5in',
    height: '11in',
    widthPx: 816,       // 8.5 * 96
    heightPx: 1056,     // 11 * 96
    margins: {
      top: 96,          // 1in = 96px
      right: 96,
      bottom: 96,
      left: 96,
    },
    usableWidthPx: 624,  // 6.5in = 624px
    usableHeightPx: 864, // 9in = 864px
  },
  a4: {
    name: 'A4',
    width: '210mm',
    height: '297mm',
    widthPx: 794,       // 210mm at 96 DPI
    heightPx: 1123,     // 297mm at 96 DPI
    margins: {
      top: 95,          // ~25mm
      right: 95,
      bottom: 95,
      left: 95,
    },
    usableWidthPx: 604,
    usableHeightPx: 933,
  },
};

// ============================================================================
// UNIFIED LETTER STYLES OPTIONS
// ============================================================================

export interface UnifiedStyleOptions {
  /** Include DRAFT watermark */
  draftMode?: boolean;
  /** Styles optimized for export (no screen-only styles) */
  forExport?: boolean;
  /** Include running headers (organization name) */
  runningHeader?: string;
  /** Include running footer (confidentiality notice) */
  runningFooter?: string;
  /** Show page numbers in footer */
  showPageNumbers?: boolean;
}

// ============================================================================
// UNIFIED LETTER STYLES - THE ONLY SOURCE FOR ALL LETTER STYLING
// ============================================================================

/**
 * Get unified letter styles for preview AND export.
 * 
 * This is the SINGLE SOURCE OF TRUTH for all letter styling.
 * Preview, PDF, DOCX, and Print all use these exact styles.
 * 
 * CRITICAL: HTML controls pagination — never the export engine.
 * 
 * @param pageSize - Page size ('letter' or 'a4')
 * @param options - Style options
 * @returns CSS string to be injected
 */
export function getUnifiedLetterStyles(
  pageSize: PageSize = 'letter',
  options: UnifiedStyleOptions = {}
): string {
  const spec = PAGE_SPECS[pageSize];
  const { 
    draftMode = false, 
    forExport = false,
    runningHeader,
    runningFooter,
    showPageNumbers = true,
  } = options;
  
  return `
    /* ══════════════════════════════════════════════════════════════════════════
       UNIFIED LETTER STYLES - SINGLE SOURCE OF TRUTH
       Generated by: paginatedLetterStyles.ts
       Page Size: ${spec.name} (${spec.width} × ${spec.height})
       Mode: ${forExport ? 'Export' : 'Preview'}${draftMode ? ' [DRAFT]' : ''}
       ══════════════════════════════════════════════════════════════════════════ */

    /* === VERTICAL RHYTHM TOKENS === */
    :root {
      --letter-space-xs: 6pt;   /* 0.5 line - within blocks */
      --letter-space-sm: 12pt;  /* 1 line - between paragraphs */
      --letter-space-md: 18pt;  /* 1.5 lines - between sections */
      --letter-space-lg: 24pt;  /* 2 lines - major separations */
      --letter-space-xl: 36pt;  /* 3 lines - after letterhead, signature space */
      --letter-line-height: 1.5;
      --letter-base-size: 12pt;
    }

    /* ═══════════════════════════════════════════════════════════════════════════
       PROFESSIONAL LETTER TYPOGRAPHY - NON-NEGOTIABLE RULES
       ═══════════════════════════════════════════════════════════════════════════
       - Body text: Left-aligned ONLY (ragged right)
       - NO text-align: justify (creates uneven spacing)
       - NO center-aligned body content  
       - Single font family per letter
       - Subject line: Bold, left-aligned
       - No decorative fonts
       ═══════════════════════════════════════════════════════════════════════════ */

    /* Global typography enforcement - body content is ALWAYS left-aligned */
    .letter-document,
    .letter-document *:not(.letter-letterhead):not(.letter-letterhead *):not(.letter-footer):not(.running-header):not(.running-footer) {
      text-align: left;
    }

    /* Explicit justification prohibition */
    .letter-body,
    .letter-body *,
    .letter-content,
    .letter-content * {
      text-align: left !important;
      text-justify: none !important;
    }

    /* Subject line / Reference line: Bold, left-aligned */
    .letter-reference,
    .reference-line,
    .letter-subject {
      font-weight: bold;
      text-align: left !important;
    }

    /* === PRINT-CSS PAGE SETUP (CONTROLS ALL PAGINATION) === */
    @page {
      size: ${spec.width} ${spec.height};
      margin: ${spec.margins.top / 96}in ${spec.margins.right / 96}in ${spec.margins.bottom / 96}in ${spec.margins.left / 96}in;
      
      /* Orphan/widow control for traditional letter feel */
      orphans: 3;
      widows: 3;
      
      /* Running footer with page numbers */
      ${showPageNumbers ? `
      @bottom-center {
        content: "Page " counter(page) " of " counter(pages);
        font-family: ${LETTER_FONT_STACK};
        font-size: 9pt;
        color: #666;
      }
      ` : ''}
      
      /* Running header (from second page onward) */
      ${runningHeader ? `
      @top-center {
        content: element(running-header);
      }
      ` : ''}
      
      /* Running footer content */
      ${runningFooter ? `
      @bottom-left {
        content: element(running-footer);
      }
      ` : ''}
    }

    /* First page - no running header */
    @page:first {
      @top-center {
        content: none;
      }
    }

    /* === RUNNING ELEMENTS (POSITION OUTSIDE FLOW) === */
    .running-header {
      position: running(running-header);
      font-family: ${LETTER_FONT_STACK};
      font-size: 10pt;
      color: #666;
      text-align: center;
      padding-bottom: 0.25in;
      border-bottom: 1px solid #ddd;
    }

    .running-footer {
      position: running(running-footer);
      font-family: ${LETTER_FONT_STACK};
      font-size: 8pt;
      color: #888;
    }

    /* === ROOT DOCUMENT STYLES === */
    html, body {
      font-family: ${LETTER_FONT_STACK};
      font-size: 12pt;
      line-height: 1.5;
      color: #000 !important;
      background: ${forExport ? '#fff' : 'transparent'};
      margin: 0;
      padding: 0;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    /* === LETTER DOCUMENT CONTAINER === */
    .letter-document {
      font-family: ${LETTER_FONT_STACK};
      font-size: 12pt;
      line-height: 1.5;
      color: #000 !important;
      background: ${forExport ? '#fff' : 'transparent'};
    }

    /* === EXPLICIT PAGE CONTAINERS === */
    .page {
      width: ${spec.usableWidthPx / 96}in;
      min-height: ${spec.usableHeightPx / 96}in;
      box-sizing: border-box;
      page-break-after: always;
      break-after: page;
    }

    .page:last-child {
      page-break-after: auto;
      break-after: auto;
    }

    /* Force page break */
    .force-page-break,
    .page-break {
      page-break-after: always;
      break-after: page;
      height: 0;
      margin: 0;
      padding: 0;
      visibility: hidden;
    }

    /* === LETTERHEAD === */
    /* Vertical Rhythm: 3 lines (36pt) after letterhead */
    .letter-letterhead {
      margin-bottom: var(--letter-space-xl, 36pt);
      text-align: center;
    }

    .letter-letterhead img {
      max-height: 60px;
      max-width: 200px;
      margin-bottom: var(--letter-space-xs, 6pt);
    }

    .letter-letterhead .org-name {
      font-weight: bold;
      font-size: 16pt;
      margin-bottom: 4px;
      color: #000 !important;
    }

    .letter-letterhead .org-info {
      font-size: 10pt;
      color: #333 !important;
      line-height: 1.4;
    }

    .letter-letterhead hr {
      margin-top: var(--letter-space-md, 18pt);
      border: none;
      border-top: 1px solid #333;
    }

    /* === DATE BLOCK (Single Authoritative Date) === */
    /* RULE: Exactly one primary date, left-aligned, below letterhead */
    /* Vertical Rhythm: 2 lines (24pt) after date */
    .letter-date {
      text-align: left;
      margin-bottom: var(--letter-space-lg, 24pt);
      color: #000 !important;
    }

    /* === RECIPIENT BLOCK === */
    /* Vertical Rhythm: 1.5 lines (18pt) after recipient */
    .letter-recipient {
      margin-bottom: var(--letter-space-md, 18pt);
      line-height: 1.4;
      color: #000 !important;
    }

    /* === REFERENCE LINE === */
    /* Vertical Rhythm: 1 line (12pt) after reference */
    .letter-reference,
    .reference-line {
      margin-bottom: var(--letter-space-sm, 12pt);
      font-weight: bold;
      color: #000 !important;
    }

    /* === SALUTATION === */
    /* Vertical Rhythm: 1 line (12pt) after salutation */
    .letter-salutation {
      margin-bottom: var(--letter-space-sm, 12pt);
      color: #000 !important;
    }

    /* === BODY CONTENT === */
    /* PROFESSIONAL LETTER TYPOGRAPHY: Left-aligned, ragged right - NON-NEGOTIABLE */
    .letter-body {
      text-align: left;
      color: #000 !important;
    }

    /* Vertical Rhythm: 1 line (12pt) between paragraphs */
    .letter-body p {
      margin-bottom: var(--letter-space-sm, 12pt);
      text-indent: 0;
      text-align: left;
      color: #000 !important;
      /* Widows and orphans control */
      widows: 3;
      orphans: 3;
    }

    .letter-body p + p {
      text-indent: 0;
    }

    /* Last paragraph before signature - prevent orphaning signature */
    .letter-body p:last-of-type {
      break-after: avoid !important;
      page-break-after: avoid !important;
    }

    /* === SECTION HEADINGS === */
    /* Vertical Rhythm: 1.5 lines (18pt) before, 0.5 lines (6pt) after */
    .letter-body .section-heading,
    .letter-body h3,
    .letter-body h4 {
      font-weight: bold;
      margin-top: var(--letter-space-md, 18pt);
      margin-bottom: var(--letter-space-xs, 6pt);
      text-align: left;
      color: #000 !important;
      /* Keep headings with following content */
      break-after: avoid !important;
      page-break-after: avoid !important;
    }

    /* === LEGAL CITATIONS === */
    .legal-citation,
    .statute-reference {
      font-style: italic;
      color: #000 !important;
    }

    /* Validation styling (only in preview mode) */
    ${!forExport ? `
    .statute-reference[data-validated="false"] {
      background-color: #fff3cd;
      border-bottom: 2px dashed #856404;
    }
    ` : `
    .statute-reference[data-validated="false"] {
      background-color: transparent;
      border-bottom: none;
    }
    `}

    /* === LISTS === */
    .letter-body ul,
    .letter-body ol {
      margin-left: 0.5in;
      margin-bottom: 1em;
      color: #000 !important;
    }

    .letter-body li {
      margin-bottom: 0.5em;
      color: #000 !important;
    }

    /* === NDA-SPECIFIC STYLES === */
    .nda-clause {
      margin-bottom: 1em;
      break-inside: avoid !important;
      page-break-inside: avoid !important;
    }

    .nda-clause-number {
      font-weight: bold;
    }

    .nda-parties {
      margin-bottom: 1em;
    }

    /* === SIGNATURE BLOCK === */
    /* Vertical Rhythm: 2 lines (24pt) before closing, 3 lines (36pt) signature space */
    /* RULE: Signature block must NEVER orphan to a new page alone */
    .letter-signature {
      margin-top: var(--letter-space-lg, 24pt);
      break-inside: avoid !important;
      page-break-inside: avoid !important;
      break-before: avoid !important;
      page-break-before: avoid !important;
      color: #000 !important;
    }

    .letter-signature .closing {
      margin-bottom: var(--letter-space-xl, 36pt);
    }

    .signature-line {
      border-bottom: 1px solid #000;
      width: 3in;
      height: var(--letter-space-xl, 36pt);
      margin-bottom: var(--letter-space-xs, 6pt);
    }

    .signature-name {
      font-weight: bold;
      margin-bottom: 3pt;
      color: #000 !important;
    }

    .signature-title {
      font-style: italic;
      color: #000 !important;
    }

    /* Keep signature components together */
    .letter-signature .closing,
    .letter-signature .signature-line,
    .letter-signature .signature-name,
    .letter-signature .signature-title {
      break-inside: avoid !important;
      page-break-inside: avoid !important;
    }

    /* === FOOTER / CONFIDENTIALITY === */
    /* Vertical Rhythm: 2 lines (24pt) before footer */
    .letter-footer {
      margin-top: var(--letter-space-lg, 24pt);
      padding-top: var(--letter-space-xs, 6pt);
      border-top: 1px solid #ccc;
      font-size: 9pt;
      color: #666 !important;
      text-align: center;
    }

    /* === MANDATORY PAGE BREAK RULES === */
    
    /* Elements that MUST stay together */
    .avoid-break,
    .keep-together,
    .letter-signature,
    .signature-block,
    .nda-clause,
    .statutory-block,
    .statutory-language {
      break-inside: avoid !important;
      page-break-inside: avoid !important;
    }

    /* Elements that force new pages */
    .page-break-before,
    .new-page {
      break-before: page !important;
      page-break-before: always !important;
    }

    .page-break-after {
      break-after: page !important;
      page-break-after: always !important;
    }

    /* Tables should avoid breaking */
    table {
      break-inside: avoid;
      page-break-inside: avoid;
    }

    /* === DRAFT WATERMARK === */
    ${draftMode ? `
    .letter-document::before {
      content: "DRAFT";
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%) rotate(-45deg);
      font-size: 120pt;
      color: rgba(200, 200, 200, 0.3);
      pointer-events: none;
      z-index: 1000;
    }
    ` : ''}

    /* === PRINT OPTIMIZATION === */
    @media print {
      html, body {
        margin: 0;
        padding: 0;
      }
      
      .letter-document {
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
        padding: 0;
        max-width: none;
      }

      .no-print {
        display: none !important;
      }
    }
  `;
}

// ============================================================================
// PAGED MEDIA STYLES (for Paged.js rendering)
// ============================================================================

/**
 * @deprecated Use getUnifiedLetterStyles() instead.
 * This function is kept for backwards compatibility only.
 */
export function getPagedMediaStyles(pageSize: PageSize = 'letter'): string {
  // Delegate to unified styles for consistency
  return getUnifiedLetterStyles(pageSize, { forExport: false });
}

// ============================================================================
// PAGE VIEWER STYLES (for displaying pages in preview)
// ============================================================================

export function getPageViewerStyles(pageSize: PageSize = 'letter'): string {
  const spec = PAGE_SPECS[pageSize];
  
  return `
    /* === PAGED.JS PAGE CONTAINER === */
    .pagedjs_pages {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 40px;
      padding: 40px;
      background: #525659;
    }

    /* === INDIVIDUAL PAGE STYLING === */
    .pagedjs_page {
      width: ${spec.widthPx}px !important;
      min-height: ${spec.heightPx}px !important;
      max-width: ${spec.widthPx}px !important;
      background: white !important;
      box-shadow: 
        0 4px 6px -1px rgba(0, 0, 0, 0.1),
        0 2px 4px -1px rgba(0, 0, 0, 0.06),
        0 0 0 1px rgba(0, 0, 0, 0.05);
      border-radius: 2px;
      position: relative;
    }

    /* === PAGE BREAK INDICATOR (Preview Only) === */
    .pagedjs_page:not(:last-child)::before {
      content: "Page Break";
      position: absolute;
      bottom: -24px;
      left: 50%;
      transform: translateX(-50%);
      font-size: 10px;
      color: rgba(99, 102, 241, 0.7);
      font-family: system-ui, -apple-system, sans-serif;
      white-space: nowrap;
      pointer-events: none;
      z-index: 5;
      background: #525659;
      padding: 0 12px;
      letter-spacing: 0.5px;
      text-transform: uppercase;
    }

    /* Dotted line between pages */
    .pagedjs_page:not(:last-child) {
      margin-bottom: 0;
    }
    
    .pagedjs_page:not(:last-child) + .pagedjs_page::before {
      /* Line extends from previous page */
    }

    .pagedjs_pages::after {
      display: none; /* Hide any default pseudo content */
    }

    /* Visual dotted line indicator */
    .pagedjs_page:not(:last-child) {
      border-bottom: 2px dashed rgba(99, 102, 241, 0.35);
      border-bottom-left-radius: 0;
      border-bottom-right-radius: 0;
    }

    /* === PAGE NUMBER BADGE === */
    .pagedjs_page::after {
      content: attr(data-page-number);
      position: absolute;
      bottom: -36px;
      left: 50%;
      transform: translateX(-50%);
      font-size: 11px;
      color: #9ca3af;
      font-family: system-ui, -apple-system, sans-serif;
      background: rgba(255, 255, 255, 0.1);
      padding: 4px 12px;
      border-radius: 4px;
      white-space: nowrap;
    }

    /* === PAGE CONTENT AREA === */
    .pagedjs_page_content {
      color: #000 !important;
      background: white !important;
    }

    .pagedjs_page_content * {
      color: inherit;
    }

    /* === RESET DARK MODE INTERFERENCE === */
    .pagedjs_page,
    .pagedjs_page * {
      color-scheme: light;
    }

    /* === PAGE MARGIN BOXES (for running headers/footers) === */
    .pagedjs_margin-top-center,
    .pagedjs_margin-bottom-center {
      font-family: ${LETTER_FONT_STACK};
      font-size: 10pt;
      color: #666;
    }
  `;
}

// ============================================================================
// PDF EXPORT OPTIONS (uses same PAGE_SPECS for consistency)
// ============================================================================

/**
 * @deprecated PDF export now uses Paged.js rendering for consistency.
 * This function is kept for fallback only.
 */
export function getPdfExportOptions(filename: string, pageSize: PageSize = 'letter') {
  const spec = PAGE_SPECS[pageSize];
  
  return {
    margin: 0, // Margins are in the HTML document itself
    filename: `${filename}.pdf`,
    image: { type: 'jpeg' as const, quality: 0.98 },
    html2canvas: {
      scale: 2,
      useCORS: true,
      letterRendering: true,
      logging: false,
      width: spec.widthPx,
    },
    jsPDF: {
      unit: 'in' as const,
      format: pageSize as 'letter' | 'a4',
      orientation: 'portrait' as const,
    },
    pagebreak: {
      mode: ['avoid-all', 'css', 'legacy'] as const,
      avoid: ['.avoid-break', '.letter-signature', '.nda-clause'],
    },
  };
}

// ============================================================================
// RUNNING ELEMENTS HELPER
// ============================================================================

/**
 * Wrap letter body with running header/footer elements for print pagination.
 * 
 * Running elements are positioned outside the normal flow and repeat
 * on each page using CSS Paged Media (@page margin boxes).
 * 
 * @param bodyHtml - The letter body HTML content
 * @param options - Running element options
 * @returns HTML with running elements injected
 */
export function wrapWithRunningElements(
  bodyHtml: string,
  options: {
    headerText?: string;
    footerText?: string;
    confidentialityNotice?: string;
  } = {}
): string {
  const { headerText, footerText, confidentialityNotice } = options;
  
  const runningHeader = headerText ? `
    <div class="running-header">${headerText}</div>
  ` : '';
  
  const runningFooter = (footerText || confidentialityNotice) ? `
    <div class="running-footer">
      ${footerText || ''}
      ${confidentialityNotice ? `<span class="confidential">${confidentialityNotice}</span>` : ''}
    </div>
  ` : '';
  
  return `
    ${runningHeader}
    ${runningFooter}
    <div class="letter-body-content">
      ${bodyHtml}
    </div>
  `;
}
