import { useState, useEffect } from "react";
import { format } from "date-fns";
import { supabase } from "@/integrations/supabase/client";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { FileText, Eye, Clock, Plus } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { getCaseReportInstances, ReportInstance } from "@/lib/reportEngine";
import { ReportInstanceViewer } from "@/components/templates/ReportInstanceViewer";

interface CaseReportsProps {
  caseId: string;
  isClosedCase?: boolean;
  onGenerateReport?: () => void;
}

export function CaseReports({ caseId, isClosedCase, onGenerateReport }: CaseReportsProps) {
  const [reports, setReports] = useState<ReportInstance[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState<ReportInstance | null>(null);
  const [viewerOpen, setViewerOpen] = useState(false);
  const [userProfiles, setUserProfiles] = useState<Record<string, string>>({});

  useEffect(() => {
    fetchReports();
    fetchUserProfiles();
  }, [caseId]);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const data = await getCaseReportInstances(caseId);
      setReports(data);
    } catch (error) {
      console.error("Error fetching reports:", error);
      toast({
        title: "Error",
        description: "Failed to load reports",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const fetchUserProfiles = async () => {
    try {
      const { data } = await supabase
        .from("profiles")
        .select("id, full_name, email");

      const profiles: Record<string, string> = {};
      (data || []).forEach(p => {
        profiles[p.id] = p.full_name || p.email;
      });
      setUserProfiles(profiles);
    } catch (error) {
      console.error("Error fetching profiles:", error);
    }
  };

  const handleViewReport = (report: ReportInstance) => {
    setSelectedReport(report);
    setViewerOpen(true);
  };

  if (loading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-32 w-full" />
      </div>
    );
  }

  if (reports.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <FileText className="h-12 w-12 text-muted-foreground mb-4" />
        <h3 className="text-lg font-semibold mb-2">No Reports Generated</h3>
        <p className="text-sm text-muted-foreground max-w-md mb-4">
          Generate your first report using a structured template to create professional case documentation.
        </p>
        {onGenerateReport && (
          <Button onClick={onGenerateReport} disabled={isClosedCase}>
            <Plus className="h-4 w-4 mr-2" />
            Generate Report
          </Button>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold">Generated Reports</h3>
        <div className="flex items-center gap-2">
          <Badge variant="secondary">{reports.length} reports</Badge>
          {onGenerateReport && (
            <Button onClick={onGenerateReport} disabled={isClosedCase} size="sm">
              <Plus className="h-4 w-4 mr-2" />
              Generate Report
            </Button>
          )}
        </div>
      </div>

      <div className="border rounded-md">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report Title</TableHead>
              <TableHead>Template</TableHead>
              <TableHead>Generated</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {reports.map((report) => (
              <TableRow key={report.id}>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4 text-muted-foreground" />
                    <span className="font-medium">{report.title}</span>
                  </div>
                </TableCell>
                <TableCell>
                  <Badge variant="outline">
                    {report.templateSnapshot?.name || 'Unknown Template'}
                  </Badge>
                </TableCell>
                <TableCell>
                  <div className="flex items-center gap-1 text-sm text-muted-foreground">
                    <Clock className="h-3 w-3" />
                    {format(report.generatedAt, "MMM d, yyyy 'at' h:mm a")}
                  </div>
                </TableCell>
                <TableCell>
                  <span className="text-sm">
                    {userProfiles[report.userId] || 'Unknown'}
                  </span>
                </TableCell>
                <TableCell>
                  {report.exportedAt ? (
                    <Badge variant="secondary">
                      Exported ({report.exportFormat?.toUpperCase()})
                    </Badge>
                  ) : (
                    <Badge variant="outline">Ready</Badge>
                  )}
                </TableCell>
                <TableCell className="text-right">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleViewReport(report)}
                  >
                    <Eye className="h-4 w-4 mr-1" />
                    View
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {/* Report Viewer Dialog */}
      <ReportInstanceViewer
        open={viewerOpen}
        onOpenChange={setViewerOpen}
        report={selectedReport}
      />
    </div>
  );
}
