import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useOrganization } from "@/contexts/OrganizationContext";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { format, parseISO } from "date-fns";
import { useNavigate } from "react-router-dom";
import { FileText, ExternalLink, Download } from "lucide-react";
import { Button } from "@/components/ui/button";

interface TimeRangeProps {
  startDate: Date;
  endDate: Date;
}

interface ReportDetailsTableProps {
  timeRange: TimeRangeProps;
}

export function ReportDetailsTable({ timeRange }: ReportDetailsTableProps) {
  const { organization } = useOrganization();
  const navigate = useNavigate();

  const { data: reports, isLoading } = useQuery({
    queryKey: ["report-details", organization?.id, timeRange.startDate, timeRange.endDate],
    queryFn: async () => {
      if (!organization?.id) return [];

      const { data, error } = await supabase
        .from("generated_reports")
        .select(`
          id,
          title,
          generated_at,
          case_id,
          user_id,
          template_id,
          cases!inner(case_number, title)
        `)
        .eq("organization_id", organization.id)
        .gte("generated_at", timeRange.startDate.toISOString())
        .lte("generated_at", timeRange.endDate.toISOString())
        .order("generated_at", { ascending: false })
        .limit(100);

      if (error) throw error;

      const userIds = [...new Set(data?.map(r => r.user_id) || [])];
      const { data: profiles } = await supabase
        .from("profiles")
        .select("id, full_name, email")
        .in("id", userIds);

      const profileMap = new Map(profiles?.map(p => [p.id, p]) || []);

      return data?.map(report => {
        const caseData = report.cases as { case_number: string; title: string } | null;
        const profile = profileMap.get(report.user_id);
        
        return {
          id: report.id,
          title: report.title,
          caseId: report.case_id,
          caseNumber: caseData?.case_number || "Unknown",
          caseTitle: caseData?.title || "Unknown",
          generatedBy: profile?.full_name || profile?.email || "Unknown",
          generatedAt: report.generated_at,
        };
      }) || [];
    },
    enabled: !!organization?.id,
  });

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Report Generation Details
          </CardTitle>
          <CardDescription>All reports generated in the selected time period</CardDescription>
        </CardHeader>
        <CardContent>
          <Skeleton className="h-[400px] w-full" />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Report Generation Details
        </CardTitle>
        <CardDescription>All reports generated in the selected time period</CardDescription>
      </CardHeader>
      <CardContent>
        {!reports || reports.length === 0 ? (
          <div className="h-[200px] flex items-center justify-center text-muted-foreground">
            No reports generated in this time period
          </div>
        ) : (
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report Title</TableHead>
                  <TableHead>Case</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Generated At</TableHead>
                  <TableHead className="w-[50px]"></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {reports.map(report => (
                  <TableRow key={report.id}>
                    <TableCell className="font-medium max-w-[200px] truncate" title={report.title}>
                      {report.title}
                    </TableCell>
                    <TableCell>
                      <button
                        onClick={() => navigate(`/cases/${report.caseId}?tab=reports`)}
                        className="text-primary hover:underline text-left"
                      >
                        {report.caseNumber}
                      </button>
                    </TableCell>
                    <TableCell>{report.generatedBy}</TableCell>
                    <TableCell className="text-muted-foreground">
                      {format(parseISO(report.generatedAt), "MMM d, yyyy h:mm a")}
                    </TableCell>
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => navigate(`/cases/${report.caseId}?tab=reports`)}
                      >
                        <ExternalLink className="h-4 w-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </CardContent>
    </Card>
  );
}