-- Add ai_tags column to case_attachments table for AI-generated tags
ALTER TABLE case_attachments 
ADD COLUMN ai_tags text[] DEFAULT NULL;

COMMENT ON COLUMN case_attachments.ai_tags IS 'Tags generated by AI analysis - displayed with AI visual styling';