import { ReactNode } from "react";
import { cn } from "@/lib/utils";
import { formatDate } from "@/lib/formatters";

interface PrintLayoutProps {
  children: ReactNode;
  title?: string;
  subtitle?: string;
  logo?: string;
  className?: string;
  showDate?: boolean;
  showPageNumbers?: boolean;
  watermark?: string;
}

export function PrintLayout({
  children,
  title,
  subtitle,
  logo,
  className,
  showDate = true,
  showPageNumbers = true,
  watermark,
}: PrintLayoutProps) {
  return (
    <div className={cn("print-layout", className)}>
      {/* Watermark (only visible in print) */}
      {watermark && (
        <div className="print-watermark hidden print:block">{watermark}</div>
      )}

      {/* Print Header */}
      {(title || logo) && (
        <header className="print-header print-no-break">
          <div className="print-invoice-header">
            <div>
              {logo && (
                <img
                  src={logo}
                  alt="Company Logo"
                  className="h-12 w-auto mb-2 print-bg"
                />
              )}
              {title && (
                <h1 className="text-2xl font-bold text-foreground">{title}</h1>
              )}
              {subtitle && (
                <p className="text-sm text-muted-foreground mt-1">{subtitle}</p>
              )}
            </div>
            {showDate && (
              <div className="text-right text-sm text-muted-foreground">
                <p>Printed: {formatDate(new Date(), "long")}</p>
                <p>Time: {formatDate(new Date(), "time")}</p>
              </div>
            )}
          </div>
        </header>
      )}

      {/* Main Content */}
      <main className="print-content">{children}</main>

      {/* Print Footer */}
      <footer className="print-footer hidden print:block">
        <div className="flex justify-between items-center">
          <span className="text-xs text-muted-foreground">
            Generated by PI Case Manager
          </span>
          {showPageNumbers && (
            <span className="text-xs text-muted-foreground">
              Page <span className="page-number"></span>
            </span>
          )}
        </div>
      </footer>
    </div>
  );
}

// Print Section Component for logical groupings
interface PrintSectionProps {
  children: ReactNode;
  title?: string;
  className?: string;
  breakBefore?: boolean;
  breakAfter?: boolean;
}

export function PrintSection({
  children,
  title,
  className,
  breakBefore = false,
  breakAfter = false,
}: PrintSectionProps) {
  return (
    <section
      className={cn(
        "print-section print-no-break mb-6",
        breakBefore && "print-break-before",
        breakAfter && "print-break-after",
        className
      )}
    >
      {title && <h2 className="print-section-title">{title}</h2>}
      {children}
    </section>
  );
}

// Print Table Component with proper styling
interface PrintTableColumn<T> {
  header: string;
  accessor: keyof T | ((item: T) => ReactNode);
  className?: string;
  align?: "left" | "center" | "right";
  width?: string;
}

interface PrintTableProps<T> {
  data: T[];
  columns: PrintTableColumn<T>[];
  className?: string;
  striped?: boolean;
  showRowNumbers?: boolean;
}

export function PrintTable<T>({
  data,
  columns,
  className,
  striped = true,
  showRowNumbers = false,
}: PrintTableProps<T>) {
  const getCellValue = (item: T, accessor: PrintTableColumn<T>["accessor"]): ReactNode => {
    if (typeof accessor === "function") {
      return accessor(item);
    }
    return item[accessor] as ReactNode;
  };

  return (
    <table className={cn("print-table", className)}>
      <thead>
        <tr>
          {showRowNumbers && <th className="w-12 text-center">#</th>}
          {columns.map((col, index) => (
            <th
              key={index}
              className={cn(
                col.align === "right" && "text-right",
                col.align === "center" && "text-center",
                col.className
              )}
              style={{ width: col.width }}
            >
              {col.header}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {data.map((item, rowIndex) => (
          <tr key={rowIndex} className={striped && rowIndex % 2 === 1 ? "bg-neutral-50" : ""}>
            {showRowNumbers && (
              <td className="text-center text-muted-foreground">{rowIndex + 1}</td>
            )}
            {columns.map((col, colIndex) => (
              <td
                key={colIndex}
                className={cn(
                  col.align === "right" && "text-right",
                  col.align === "center" && "text-center",
                  col.className
                )}
              >
                {getCellValue(item, col.accessor)}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

// Print Actions Component (hide in print, show on screen)
interface PrintActionsProps {
  onPrint?: () => void;
  onExportPdf?: () => void;
  className?: string;
}

export function PrintActions({
  onPrint,
  onExportPdf,
  className,
}: PrintActionsProps) {
  const handlePrint = () => {
    if (onPrint) {
      onPrint();
    } else {
      window.print();
    }
  };

  return (
    <div className={cn("print-hidden flex items-center gap-2", className)}>
      <button
        onClick={handlePrint}
        className="inline-flex items-center gap-2 px-4 py-2 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <polyline points="6 9 6 2 18 2 18 9" />
          <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
          <rect x="6" y="14" width="12" height="8" />
        </svg>
        Print
      </button>
      {onExportPdf && (
        <button
          onClick={onExportPdf}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-md border border-border bg-background hover:bg-muted transition-colors"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
            <polyline points="14 2 14 8 20 8" />
            <line x1="12" y1="18" x2="12" y2="12" />
            <line x1="9" y1="15" x2="15" y2="15" />
          </svg>
          Export PDF
        </button>
      )}
    </div>
  );
}

// Invoice Total Component for print layouts
interface PrintInvoiceTotalProps {
  subtotal: number;
  tax?: number;
  taxRate?: number;
  discount?: number;
  total: number;
  amountPaid?: number;
  balanceDue?: number;
  currency?: string;
  className?: string;
}

export function PrintInvoiceTotal({
  subtotal,
  tax,
  taxRate,
  discount,
  total,
  amountPaid,
  balanceDue,
  currency = "USD",
  className,
}: PrintInvoiceTotalProps) {
  const formatAmount = (amount: number) =>
    new Intl.NumberFormat("en-US", {
      style: "currency",
      currency,
    }).format(amount);

  return (
    <div className={cn("mt-8 flex justify-end", className)}>
      <div className="w-64">
        <div className="flex justify-between py-2 border-b">
          <span className="text-muted-foreground">Subtotal</span>
          <span className="number-display">{formatAmount(subtotal)}</span>
        </div>
        {discount !== undefined && discount > 0 && (
          <div className="flex justify-between py-2 border-b text-success">
            <span>Discount</span>
            <span className="number-display">-{formatAmount(discount)}</span>
          </div>
        )}
        {tax !== undefined && (
          <div className="flex justify-between py-2 border-b">
            <span className="text-muted-foreground">
              Tax {taxRate && `(${taxRate}%)`}
            </span>
            <span className="number-display">{formatAmount(tax)}</span>
          </div>
        )}
        <div className="flex justify-between py-3 border-b-2 border-foreground font-semibold text-lg">
          <span>Total</span>
          <span className="number-display">{formatAmount(total)}</span>
        </div>
        {amountPaid !== undefined && amountPaid > 0 && (
          <div className="flex justify-between py-2 text-success">
            <span>Amount Paid</span>
            <span className="number-display">-{formatAmount(amountPaid)}</span>
          </div>
        )}
        {balanceDue !== undefined && (
          <div className="flex justify-between py-3 font-bold text-lg">
            <span>Balance Due</span>
            <span className="number-display">{formatAmount(balanceDue)}</span>
          </div>
        )}
      </div>
    </div>
  );
}
